remote_theme: pages-themes/modernist@v0.2.0

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

plugins:
  - jekyll-remote-theme

title: RPG978's homepage
description: Demonstration of computer science projects.
