package com.rpg978.reelchoice;

import android.app.Application;

import androidx.lifecycle.LiveData;

import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.function.Consumer;

/**
 * MovieRepository
 *
 * The single source for all data operations.
 * Sits between the ViewModel and Room, abstracting away database access,
 * threading and query organization
 *
 * Responsibilities:
 *   - Expose LiveData streams for the two movie lists.
 *   - Perform inserts, updates, and deletes on a background thread.
 *   - Provide one-shot operations (like RNG) without exposing Room directly.
 *   - Keep the ViewModel clean and UI-focused.
 */
public class MovieRepository {

    // DAO interface generated by Room; contains all SQL queries.
    private final MovieDao movieDao;

    // Single-thread executor ensures DB writes happen off the main thread
    // and in a predictable, serialized order.
    private final ExecutorService executor;

    // LiveData streams returned directly from Room.
    // These automatically update when the database changes.
    private final LiveData<List<Movie>> toWatchMovies;
    private final LiveData<List<Movie>> watchedMovies;

    public MovieRepository(Application application) {
        // Obtain the singleton Room database instance.
        MovieDatabase db = MovieDatabase.getInstance(application);
        movieDao = db.movieDao();

        // Background executor for all DB write operations.
        executor = Executors.newSingleThreadExecutor();

        // Query Room once - LiveData keeps itself updated.
        toWatchMovies = movieDao.getMoviesByWatched(false);
        watchedMovies = movieDao.getMoviesByWatched(true);
    }

    // Expose the "To Watch" list to the ViewModel.
    public LiveData<List<Movie>> getToWatchMovies() {
        return toWatchMovies;
    }

    // Expose the "Watched" list to the ViewModel.
    public LiveData<List<Movie>> getWatchedMovies() {
        return watchedMovies;
    }

    /**
     * Insert a new movie into the database.
     * Runs on the executor to avoid blocking the UI thread.
     */
    public void addMovie(String name) {
        executor.execute(() -> {
            Movie movie = new Movie(name);
            movie.watched = false;
            movieDao.insert(movie);
        });
    }

    /**
     * Update an existing movie (rename, toggle watched, etc.).
     * Also executed off the main thread.
     */
    public void updateMovie(Movie movie) {
        executor.execute(() -> movieDao.update(movie));
    }

    /**
     * Delete a movie from the database.
     */
    public void deleteMovie(Movie movie) {
        executor.execute(() -> movieDao.delete(movie));
    }

    /**
     * One-shot random movie request.
     *
     * This is intentionally NOT LiveData because randomness is an event,
     * not a persistent state. The repository performs the query on a
     * background thread and returns the result via callback.
     */
    public void getRandomMovie(Consumer<Movie> callback) {
        executor.execute(() -> {
            Movie movie = movieDao.getRandomMovie();
            callback.accept(movie);
        });
    }
}
