package com.rpg978.reelchoice;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Movie
 *
 * Represents a single row in the "movies" Room database table.
 *
 * Responsibilities:
 *   - Define the schema for the Movie table.
 *   - Provide fields used by Room for persistence.
 *   - Supply identity and content comparison for DiffUtil in MovieAdapter.
 *
 * Notes:
 *   - Room requires public fields or getters/setters.
 *   - The primary key is autogenerated by SQLite.
 *   - 'watched' determines which fragment the movie appears in.
 */
@Entity(tableName = "movies")
public class Movie {

    // Primary key for the Movie table.
    // autoGenerate = true means SQLite assigns the ID on insert.
    @PrimaryKey(autoGenerate = true)
    public int id;

    // Movie title as displayed in the UI.
    @ColumnInfo(name = "name")
    public String name;

    // Whether the movie is in the "Watched" list.
    // false -> To Watch
    // true  -> Watched
    @ColumnInfo(name = "watched")
    public boolean watched;

    /**
     * Constructor used by app code when creating a new Movie.
     * Room will use this constructor when inserting new rows.
     *
     * New movies always start as "To Watch".
     */
    public Movie(String name) {
        this.name = name;
        this.watched = false;
    }

    /**
     * Equality check used by DiffUtil in MovieAdapter.
     *
     * Two Movie objects are considered equal if:
     *   - They represent the same database row (same ID)
     *   - Their fields match (name and watched)
     *
     * This ensures RecyclerView only redraws rows that actually changed.
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (!(obj instanceof Movie)) return false;
        Movie other = (Movie) obj;
        return id == other.id &&
                watched == other.watched &&
                name.equals(other.name);
    }

}

